# Generated by Django 5.2.9 on 2026-01-01 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="cons",
            field=models.TextField(
                blank=True,
                help_text="ما هي النقاط التي تحتاج لتحسين؟",
                verbose_name="السلبيات",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="helpful_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="عدد من وجد هذا التقييم مفيداً",
                verbose_name="عدد المفيد",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="is_verified_purchase",
            field=models.BooleanField(
                default=False,
                help_text="هل العميل طلب الخدمة فعلياً؟",
                verbose_name="شراء موثق",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="pros",
            field=models.TextField(
                blank=True,
                help_text="ما هي مميزات هذه الخدمة؟",
                verbose_name="الإيجابيات",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="provider_response",
            field=models.TextField(blank=True, verbose_name="رد مقدم الخدمة"),
        ),
        migrations.AddField(
            model_name="review",
            name="provider_response_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الرد"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="title",
            field=models.CharField(
                default=1,
                help_text="مثال: خدمة ممتازة وسريعة",
                max_length=200,
                verbose_name="عنوان التقييم",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
        ),
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(verbose_name="التعليق"),
        ),
        migrations.AlterField(
            model_name="review",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="العميل",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="is_approved",
            field=models.BooleanField(
                default=True,
                help_text="هل تم مراجعة والموافقة على التقييم؟",
                verbose_name="موافق عليه",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                verbose_name="التقييم",
            ),
        ),
    ]
