# Generated by Django 5.2.9 on 2026-01-31 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0006_provider_cancelled_orders_provider_completed_orders_and_more",
        ),
        ("services", "0002_review_cons_review_helpful_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="delivery_time",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="مدة التسليم"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="خدمة موثقة"),
        ),
        migrations.AddField(
            model_name="service",
            name="level",
            field=models.CharField(
                choices=[
                    ("beginner", "مبتدئ"),
                    ("intermediate", "متوسط"),
                    ("expert", "خبير"),
                    ("professional", "محترف"),
                ],
                default="intermediate",
                max_length=20,
                verbose_name="المستوى",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="orders_count",
            field=models.PositiveIntegerField(default=0, verbose_name="عدد الطلبات"),
        ),
        migrations.AddField(
            model_name="service",
            name="response_time",
            field=models.CharField(
                blank=True,
                help_text="مثال: خلال ساعة واحدة",
                max_length=50,
                verbose_name="وقت الاستجابة",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="revision_count",
            field=models.PositiveIntegerField(default=1, verbose_name="عدد المراجعات"),
        ),
        migrations.AddField(
            model_name="service",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "مسودة"),
                    ("active", "نشط"),
                    ("inactive", "غير نشط"),
                    ("archived", "مؤرشف"),
                ],
                default="draft",
                max_length=20,
                verbose_name="الحالة",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="total_reviews",
            field=models.PositiveIntegerField(default=0, verbose_name="عدد التقييمات"),
        ),
        migrations.AddField(
            model_name="service",
            name="video_intro",
            field=models.URLField(
                blank=True,
                help_text="رابط يوتيوب أو Vimeo",
                verbose_name="رابط الفيديو التعريفي",
            ),
        ),
        migrations.CreateModel(
            name="ProviderPortfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان العمل")),
                ("description", models.TextField(verbose_name="وصف العمل")),
                (
                    "image",
                    models.ImageField(upload_to="portfolio/", verbose_name="الصورة"),
                ),
                ("link", models.URLField(blank=True, verbose_name="رابط العمل")),
                (
                    "client_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="اسم العميل"
                    ),
                ),
                (
                    "completion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الإنجاز"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="مميز"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_items",
                        to="accounts.provider",
                        verbose_name="مقدم الخدمة",
                    ),
                ),
            ],
            options={
                "verbose_name": "عمل في المعرض",
                "verbose_name_plural": "معرض الأعمال",
                "ordering": ["-is_featured", "order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=300, verbose_name="السؤال")),
                ("answer", models.TextField(verbose_name="الجواب")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="services.service",
                        verbose_name="الخدمة",
                    ),
                ),
            ],
            options={
                "verbose_name": "سؤال شائع",
                "verbose_name_plural": "الأسئلة الشائعة",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ServiceFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان الميزة"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="وصف الميزة"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="اسم أيقونة Bootstrap Icons",
                        max_length=50,
                        verbose_name="الأيقونة",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="services.service",
                        verbose_name="الخدمة",
                    ),
                ),
            ],
            options={
                "verbose_name": "ميزة خدمة",
                "verbose_name_plural": "مميزات الخدمات",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ServicePackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم الباقة")),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("basic", "أساسي"),
                            ("standard", "قياسي"),
                            ("premium", "ممتاز"),
                        ],
                        default="basic",
                        max_length=20,
                        verbose_name="نوع الباقة",
                    ),
                ),
                ("description", models.TextField(verbose_name="وصف الباقة")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="السعر"
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        default=1, verbose_name="مدة التسليم (أيام)"
                    ),
                ),
                (
                    "revision_count",
                    models.PositiveIntegerField(
                        default=1, verbose_name="عدد المراجعات"
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        default=list,
                        help_text="قائمة المميزات كـ JSON",
                        verbose_name="المميزات",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="services.service",
                        verbose_name="الخدمة",
                    ),
                ),
            ],
            options={
                "verbose_name": "باقة خدمة",
                "verbose_name_plural": "باقات الخدمات",
                "ordering": ["order", "price"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=100, verbose_name="اسم العميل"),
                ),
                (
                    "customer_avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="testimonials/avatars/",
                        verbose_name="صورة العميل",
                    ),
                ),
                (
                    "customer_title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="المسمى الوظيفي"
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=5,
                        verbose_name="التقييم",
                    ),
                ),
                ("comment", models.TextField(verbose_name="التعليق")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="مميز"),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=True, verbose_name="موافق عليه"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonials",
                        to="services.service",
                        verbose_name="الخدمة",
                    ),
                ),
            ],
            options={
                "verbose_name": "شهادة عميل",
                "verbose_name_plural": "شهادات العملاء",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
    ]
