# Generated by Django 5.2.9 on 2025-12-19 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=100, verbose_name="الاسم المعروض"),
                ),
                ("bio", models.TextField(blank=True, verbose_name="نبذة تعريفية")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="providers/avatars/",
                        verbose_name="الصورة الشخصية",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="موثق"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "مقدم خدمة",
                "verbose_name_plural": "مقدمو الخدمات",
                "ordering": ["-created_at"],
            },
        ),
    ]
