# Generated by Django 5.2.9 on 2026-01-01 09:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profiles/pictures/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                        verbose_name="الصورة الشخصية",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الميلاد"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "ذكر"), ("female", "أنثى"), ("other", "آخر")],
                        max_length=10,
                        verbose_name="الجنس",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="+966XXXXXXXXX",
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="رقم الهاتف يجب أن يكون بالصيغة: +966XXXXXXXXX",
                                regex="^\\+?966?[0-9]{9,10}$",
                            )
                        ],
                        verbose_name="رقم الهاتف",
                    ),
                ),
                (
                    "alternate_phone",
                    models.CharField(
                        blank=True,
                        help_text="+966XXXXXXXXX",
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="رقم الهاتف يجب أن يكون بالصيغة: +966XXXXXXXXX",
                                regex="^\\+?966?[0-9]{9,10}$",
                            )
                        ],
                        verbose_name="رقم هاتف بديل",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="الشارع، رقم المبنى، إلخ",
                        verbose_name="العنوان التفصيلي",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="المدينة"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="الحي/المنطقة"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="الرمز البريدي"
                    ),
                ),
                (
                    "id_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("national_id", "بطاقة الهوية الوطنية"),
                            ("passport", "جواز السفر"),
                            ("iqama", "الإقامة"),
                        ],
                        max_length=20,
                        verbose_name="نوع الوثيقة",
                    ),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True,
                        help_text="رقم الهوية/الجواز/الإقامة",
                        max_length=20,
                        verbose_name="رقم الوثيقة",
                    ),
                ),
                (
                    "id_document",
                    models.ImageField(
                        blank=True,
                        help_text="صورة الهوية أو الجواز أو الإقامة (JPG, PNG, PDF - حد أقصى 5MB)",
                        null=True,
                        upload_to="profiles/documents/ids/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "pdf"]
                            )
                        ],
                        verbose_name="صورة الوثيقة",
                    ),
                ),
                (
                    "id_verified",
                    models.BooleanField(
                        default=False, verbose_name="تم التحقق من الهوية"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ التحقق"
                    ),
                ),
                (
                    "verification_notes",
                    models.TextField(
                        blank=True,
                        help_text="ملاحظات الموظف حول التحقق من الوثيقة",
                        verbose_name="ملاحظات التحقق",
                    ),
                ),
                (
                    "profile_completed",
                    models.BooleanField(
                        default=False, verbose_name="الملف الشخصي مكتمل"
                    ),
                ),
                (
                    "completion_percentage",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="نسبة الاكتمال"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_profiles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم التحقق بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "الملف الشخصي",
                "verbose_name_plural": "الملفات الشخصية",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_verify_documents", "يمكنه التحقق من الوثائق"),
                    ("can_view_sensitive_data", "يمكنه عرض البيانات الحساسة"),
                ],
            },
        ),
    ]
