# Generated by Django 5.2.9 on 2026-01-01 13:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "الملف الشخصي",
                "verbose_name_plural": "الملفات الشخصية",
            },
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="address",
            field=models.TextField(blank=True, verbose_name="العنوان التفصيلي"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="alternate_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="رقم هاتف بديل"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="district",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="المنطقة/الحي"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="id_document",
            field=models.FileField(
                blank=True,
                help_text="JPG, PNG, أو PDF - حد أقصى 5MB",
                null=True,
                upload_to="documents/ids/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "pdf"]
                    )
                ],
                verbose_name="صورة الوثيقة",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="id_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="رقم الوثيقة"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="يرجى إدخال رقم هاتف عراقي صحيح (مثال: 07XXXXXXXXX)",
                        regex="^(\\+964|0)?7[3-9]\\d{8}$",
                    )
                ],
                verbose_name="رقم الهاتف",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profiles/pictures/",
                verbose_name="الصورة الشخصية",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="verification_notes",
            field=models.TextField(blank=True, verbose_name="ملاحظات التحقق"),
        ),
        migrations.CreateModel(
            name="ProviderAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="الاسم الكامل"),
                ),
                (
                    "national_id",
                    models.CharField(max_length=50, verbose_name="رقم البطاقة الموحدة"),
                ),
                ("address", models.TextField(verbose_name="عنوان السكن الكامل")),
                (
                    "phone_number",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="يرجى إدخال رقم هاتف عراقي صحيح",
                                regex="^(\\+964|0)?7[3-9]\\d{8}$",
                            )
                        ],
                        verbose_name="رقم الهاتف",
                    ),
                ),
                (
                    "specialty",
                    models.CharField(max_length=200, verbose_name="التخصص المهني"),
                ),
                (
                    "conduct_agreement",
                    models.BooleanField(
                        default=False,
                        help_text="أتعهد بحسن السيرة والسلوك واحترام حرمة المنازل",
                        verbose_name="الالتزام بالسلوك العام",
                    ),
                ),
                (
                    "professional_standards",
                    models.BooleanField(
                        default=False,
                        help_text="أتعهد بالالتزام بقائمة الأسعار الثابتة وتقديم خدمة عالية الجودة",
                        verbose_name="الالتزام بالمعايير المهنية",
                    ),
                ),
                (
                    "commission_agreement",
                    models.BooleanField(
                        default=False,
                        help_text="أقر بعمولة المنصة وعدم الاتفاق خارج المنصة",
                        verbose_name="الالتزام المالي",
                    ),
                ),
                (
                    "privacy_agreement",
                    models.BooleanField(
                        default=False,
                        help_text="أتعهد بعدم استخدام بيانات العملاء لأغراض شخصية",
                        verbose_name="سرية البيانات",
                    ),
                ),
                (
                    "commission_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        max_digits=5,
                        verbose_name="نسبة العمولة %",
                    ),
                ),
                (
                    "commission_fixed",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="مبلغ العمولة الثابت (دينار)",
                    ),
                ),
                (
                    "id_card_front",
                    models.ImageField(
                        upload_to="agreements/id_cards/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "pdf"]
                            )
                        ],
                        verbose_name="صورة البطاقة - الوجه الأمامي",
                    ),
                ),
                (
                    "id_card_back",
                    models.ImageField(
                        blank=True,
                        upload_to="agreements/id_cards/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "pdf"]
                            )
                        ],
                        verbose_name="صورة البطاقة - الوجه الخلفي",
                    ),
                ),
                (
                    "signature_image",
                    models.ImageField(
                        blank=True,
                        upload_to="agreements/signatures/%Y/%m/",
                        verbose_name="صورة التوقيع",
                    ),
                ),
                (
                    "thumbprint_image",
                    models.ImageField(
                        blank=True,
                        upload_to="agreements/thumbprints/%Y/%m/",
                        verbose_name="صورة بصمة الإبهام",
                    ),
                ),
                (
                    "signed_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاريخ التوقيع"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ التحقق"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات الإدارة")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "provider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreement",
                        to="accounts.provider",
                        verbose_name="مقدم الخدمة",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_agreements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم التحقق بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "تعهد مقدم خدمة",
                "verbose_name_plural": "تعهدات مقدمي الخدمات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProviderViolation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "violation_type",
                    models.CharField(
                        choices=[
                            ("conduct", "مخالفة سلوكية"),
                            ("quality", "مخالفة جودة العمل"),
                            ("pricing", "مخالفة الأسعار"),
                            ("commission", "التهرب من العمولة"),
                            ("privacy", "انتهاك الخصوصية"),
                            ("other", "أخرى"),
                        ],
                        max_length=20,
                        verbose_name="نوع المخالفة",
                    ),
                ),
                ("description", models.TextField(verbose_name="وصف المخالفة")),
                (
                    "severity",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "بسيطة"), (2, "متوسطة"), (3, "خطيرة")],
                        default=1,
                        verbose_name="درجة الخطورة",
                    ),
                ),
                (
                    "evidence",
                    models.FileField(
                        blank=True, upload_to="violations/%Y/%m/", verbose_name="الدليل"
                    ),
                ),
                (
                    "action_taken",
                    models.TextField(blank=True, verbose_name="الإجراء المتخذ"),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="تم الحل"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التسجيل"
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violations",
                        to="accounts.provider",
                        verbose_name="مقدم الخدمة",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_violations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المبلغ",
                    ),
                ),
            ],
            options={
                "verbose_name": "مخالفة",
                "verbose_name_plural": "المخالفات",
                "ordering": ["-created_at"],
            },
        ),
    ]
