# Generated by Django 5.2.9 on 2026-01-01 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_alter_userprofile_options_alter_userprofile_address_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="provider_approved",
            field=models.BooleanField(
                default=False,
                help_text="يجب الموافقة على المزودين قبل السماح لهم بإنشاء خدمات",
                verbose_name="موافقة مزود الخدمة",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="provider_approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ موافقة المزود"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="provider_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_provider_profiles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تمت الموافقة بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("customer", "عميل"),
                    ("provider", "مقدم خدمة"),
                    ("admin", "مدير"),
                ],
                default="customer",
                max_length=20,
                verbose_name="نوع المستخدم",
            ),
        ),
    ]
