# Generated by Django 5.2.9 on 2026-01-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userprofile_provider_approved_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="أدخل رقم هاتفك",
                max_length=20,
                verbose_name="رقم الهاتف",
            ),
        ),
    ]
