# Generated by Django 5.2.9 on 2026-01-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_userprofile_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="cancelled_orders",
            field=models.PositiveIntegerField(
                default=0, verbose_name="الطلبات الملغاة"
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="completed_orders",
            field=models.PositiveIntegerField(
                default=0, verbose_name="الطلبات المكتملة"
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="providers/covers/",
                verbose_name="صورة الغلاف",
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="السعر بالساعة",
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="instagram",
            field=models.URLField(blank=True, verbose_name="إنستغرام"),
        ),
        migrations.AddField(
            model_name="provider",
            name="languages",
            field=models.JSONField(blank=True, default=list, verbose_name="اللغات"),
        ),
        migrations.AddField(
            model_name="provider",
            name="level",
            field=models.CharField(
                choices=[
                    ("new", "مبتدئ"),
                    ("level_1", "المستوى الأول"),
                    ("level_2", "المستوى الثاني"),
                    ("level_3", "المستوى الثالث"),
                    ("top_rated", "الأعلى تقييماً"),
                ],
                default="new",
                max_length=20,
                verbose_name="المستوى",
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="linkedin",
            field=models.URLField(blank=True, verbose_name="لينكد إن"),
        ),
        migrations.AddField(
            model_name="provider",
            name="response_time",
            field=models.CharField(
                blank=True,
                help_text="مثال: خلال ساعة واحدة",
                max_length=50,
                verbose_name="وقت الاستجابة",
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="skills",
            field=models.JSONField(blank=True, default=list, verbose_name="المهارات"),
        ),
        migrations.AddField(
            model_name="provider",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="مثال: مصمم جرافيك محترف",
                max_length=150,
                verbose_name="المسمى الوظيفي",
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="total_orders",
            field=models.PositiveIntegerField(default=0, verbose_name="إجمالي الطلبات"),
        ),
        migrations.AddField(
            model_name="provider",
            name="twitter",
            field=models.URLField(blank=True, verbose_name="تويتر"),
        ),
        migrations.AddField(
            model_name="provider",
            name="website",
            field=models.URLField(blank=True, verbose_name="الموقع الإلكتروني"),
        ),
        migrations.AddField(
            model_name="provider",
            name="youtube",
            field=models.URLField(blank=True, verbose_name="يوتيوب"),
        ),
    ]
