# Generated by Django 5.2.9 on 2025-12-19 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("request_new", "طلب جديد"),
                            ("request_status", "تحديث حالة الطلب"),
                            ("request_comment", "تعليق جديد"),
                            ("system", "إشعار النظام"),
                        ],
                        default="system",
                        max_length=20,
                        verbose_name="نوع الإشعار",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                ("message", models.TextField(verbose_name="الرسالة")),
                ("link", models.URLField(blank=True, verbose_name="الرابط")),
                ("is_read", models.BooleanField(default=False, verbose_name="مقروء")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "إشعار",
                "verbose_name_plural": "الإشعارات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جديد"),
                            ("in_review", "قيد المراجعة"),
                            ("approved", "تمت الموافقة"),
                            ("rejected", "مرفوض"),
                            ("in_progress", "قيد التنفيذ"),
                            ("done", "مكتمل"),
                            ("canceled", "ملغي"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "customer_notes",
                    models.TextField(blank=True, verbose_name="ملاحظات العميل"),
                ),
                (
                    "staff_notes",
                    models.TextField(blank=True, verbose_name="ملاحظات الموظف"),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="رقم التواصل"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد الإلكتروني"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="العميل",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="services.service",
                        verbose_name="الخدمة",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب خدمة",
                "verbose_name_plural": "طلبات الخدمات",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_manage_requests", "يمكنه إدارة الطلبات"),
                    ("can_change_status", "يمكنه تغيير حالة الطلب"),
                ],
            },
        ),
        migrations.CreateModel(
            name="StatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("new", "جديد"),
                            ("in_review", "قيد المراجعة"),
                            ("approved", "تمت الموافقة"),
                            ("rejected", "مرفوض"),
                            ("in_progress", "قيد التنفيذ"),
                            ("done", "مكتمل"),
                            ("canceled", "ملغي"),
                        ],
                        max_length=20,
                        verbose_name="من حالة",
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("new", "جديد"),
                            ("in_review", "قيد المراجعة"),
                            ("approved", "تمت الموافقة"),
                            ("rejected", "مرفوض"),
                            ("in_progress", "قيد التنفيذ"),
                            ("done", "مكتمل"),
                            ("canceled", "ملغي"),
                        ],
                        max_length=20,
                        verbose_name="إلى حالة",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التغيير"
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم التغيير بواسطة",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="requests.servicerequest",
                        verbose_name="الطلب",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تغيير الحالة",
                "verbose_name_plural": "سجلات تغييرات الحالات",
                "ordering": ["-created_at"],
            },
        ),
    ]
